status = [
  'docs-build',
  'test-linux',
  'test-macos',
  'test-windows',
  'buildkite/calibrateemulatesample-ci'
]
delete_merged_branches = true
timeout_sec = 4800
block_labels = [ "do-not-merge-yet" ]
