agents:
  queue: central
  modules: climacommon/2024_03_18

env:
  OPENBLAS_NUM_THREADS: 1
  GKSwstype: nul
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/default"
  

steps:
  - label: "Init Julia + Conda + PyCall"
    key: "init"
    command: |
      
      mkdir -p "$JULIA_DEPOT_PATH"
      echo "Using depot: $JULIA_DEPOT_PATH"
      
      julia --project -e '
        using Pkg

        println("---- Instantiating root project")
        Pkg.instantiate(; verbose=true)

        println("---- Setting up Conda")
        using Conda
        Conda.add("scipy=1.17.0", channel="conda-forge")
        Conda.add("scikit-learn=1.8.0")

        println("---- Installing PyCall")
        ENV["PYTHON"] = ""
        Pkg.add("PyCall")

        # Force PyCall to use Conda.jl python
        Pkg.build("PyCall")

        using PyCall
        println("PyCall python = ", PyCall.python)
      '

  - wait

  - label: "CES - Lorenz"
    key: "lorenz"
    command: |
      
      julia --color=yes --project=examples/Lorenz -e '
        using Pkg

        println("--- Developing Project")
        Pkg.develop(path=".")
        Pkg.instantiate()

        println("+++ Running Lorenz")
        include("examples/Lorenz/calibrate.jl")
        include("examples/Lorenz/emulate_sample.jl")
      '

    artifact_paths:
      - "examples/Lorenz/output/*.png"

  - label: "Emulator - regression 2D"
    key: "emulator_compare"
    command: |
     
      julia --color=yes --project=examples/Emulator/Regression_2d_2d -e '      
        using Pkg

        println("--- Developing Project")
        Pkg.develop(path=".")
        Pkg.instantiate()

        println("+++ Running compare_regression")
        include("examples/Emulator/Regression_2d_2d/compare_regression.jl")
      '

    artifact_paths:
      - "examples/Emulator/Regression_2d_2d/output/*.png"