
agents:
  queue: central
  modules: climacommon/2025_03_18

env:
  OPENBLAS_NUM_THREADS: 1
  GKSwstype: nul
 

steps:
  - label: "Init Julia + Conda + PyCall"
    key: "init"
    command: |
      echo $$JULIA_DEPOT_PATH
      julia --project -e '
        using Pkg

        println("---- Instantiating root project")
        Pkg.instantiate(; verbose=true)

        println("---- Setting up Conda")
        using Conda
        Conda.add("python=3.11")
        Conda.add("scipy=1.17.1", channel="conda-forge")
        Conda.add("scikit-learn=1.7.0")

        println("---- Installing PyCall")
        ENV["PYTHON"] = ""
        Pkg.add("PyCall")

        # Force PyCall to use Conda.jl python
        Pkg.build("PyCall")

        using PyCall
        println("PyCall python = ", PyCall.python)
      '
      
  - wait

  - label: "CES - Lorenz"
    key: "lorenz"
    command: |
      mkdir examples/Lorenz/depot
      export JULIA_DEPOT_PATH="$(pwd)/examples/Lorenz/depot:${JULIA_DEPOT_PATH}"
      echo "PYTHON: $$PYTHON"
      echo "CONDA_JL_HOME: $$CONDA_JL_HOME"
      echo "JULIA: $$JULIA_DEPOT_PATH"

      echo "=== GCC version ==="
      gcc --version || true

      echo "=== Julia version ==="
      julia --version

      echo "=== Julia libstdc++ CXXABI versions ==="
      JULIA_STDCXX="$(julia -e 'print(joinpath(Sys.BINDIR,"..","lib","julia","libstdc++.so.6"))')"
      echo "Julia libstdc++ path: $JULIA_STDCXX"
      strings "$JULIA_STDCXX" | grep CXXABI | tail -n 5 || true

      echo "=== System libstdc++ CXXABI versions ==="
      strings /usr/lib64/libstdc++.so.6 | grep CXXABI | tail -n 5 || true

      echo "=== Conda.jl's libstdc++ CXXABI version==="
      strings ${CONDA_JL_HOME}/lib/libstdc++.so.6 | grep CXXABI

      echo "=== Loaded stdc++ from inside Julia ==="
      julia -e 'using Libdl; println(filter(x->occursin("stdc++",x), Libdl.dllist()))'

      export JULIA_USE_SYSTEM_LIBSTDCXX=1 # do not use julias libstdc++ which can be very old.
      
      
      echo "=== Loaded stdc++ from inside Julia ==="
      julia -e 'using Libdl; println(filter(x->occursin("stdc++",x), Libdl.dllist()))'

      julia --color=yes --project=examples/Lorenz -e '
        using Pkg

        println("--- Developing Project")
        Pkg.develop(path=".")
        Pkg.instantiate()
        println(ENV["PYTHON"])

        Pkg.add("PyCall")
        using PyCall
        println("PyCall python = ", PyCall.python)        
        println("+++ Running Lorenz")
        include("examples/Lorenz/calibrate.jl")
        include("examples/Lorenz/emulate_sample.jl")
      '
    env:
      PYTHON: "${JULIA_DEPOT_PATH}/conda/3/x86_64/bin/python"
      CONDA_JL_HOME: "${JULIA_DEPOT_PATH}/conda/3/x86_64/"

    artifact_paths:
      - "examples/Lorenz/output/*.png"

  - label: "Emulator - regression 2D"
    key: "emulator_compare"
    command: |
      mkdir examples/Emulator/Regression_2d_2d/depot
      export JULIA_DEPOT_PATH="$(pwd)/examples/Emulator/Regression_2d_2d/depot:${JULIA_DEPOT_PATH}"
      echo "PYTHON: $$PYTHON"
      echo "CONDA_JL_HOME: $$CONDA_JL_HOME"
      echo "JULIA: $$JULIA_DEPOT_PATH"
      
      julia --color=yes --project=examples/Emulator/Regression_2d_2d -e '      
        using Pkg

        println("--- Developing Project")
        Pkg.develop(path=".")
        Pkg.instantiate()
        println(ENV["PYTHON"])

        println("+++ Running compare_regression")
        include("examples/Emulator/Regression_2d_2d/compare_regression.jl")
      '
    env:
      PYTHON: "${JULIA_DEPOT_PATH}/conda/3/x86_64/bin/python"
      CONDA_JL_HOME: "${JULIA_DEPOT_PATH}/conda/3/x86_64/"

    artifact_paths:
      - "examples/Emulator/Regression_2d_2d/output/*.png"