env:
  JULIA_VERSION: "1.8.0"
  OPENBLAS_NUM_THREADS: 1
  GKSwstype: nul

steps:
  - label: "init project env"
    key: "init_project_env"
    command:
      - "echo $$JULIA_DEPOT_PATH"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Conda; Conda.add(\"scipy=1.8.1\")'"
      - "julia --project -e 'using Conda; Conda.add(\"scikit-learn=1.1.1\")'"
      - "julia --project -e 'using Conda; Conda.add(\"matplotlib\")'"
    env:
      PYTHON: ""
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - wait

  - label: "Lorenz"
    key: "lorenz"
    command: |
      export PYTHON="$$JULIA_DEPOT_PATH/conda/3/bin/python"
      export PYTHONHOME="$$JULIA_DEPOT_PATH/conda/3/bin"
      export CONDA_JL_HOME="$$JULIA_DEPOT_PATH/conda/3"

      mkdir examples/Lorenz/depot
      export JULIA_DEPOT_PATH="$$(pwd)/examples/Lorenz/depot:$$JULIA_DEPOT_PATH"

      julia --color=yes --project=examples/Lorenz -e '
        println("--- Developing Project")
        using Pkg;
        Pkg.develop(path=".")
        println("--- Instantiating Project")
        Pkg.instantiate()
        println("+++ Running Lorenz")
        include("examples/Lorenz/calibrate.jl")
        include("examples/Lorenz/calibrate.jl")'

    artifact_paths:
      - "examples/Lorenz/output/*.png"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: "Gaussian Process Emulator"
    key: "gaussian_process_emulator"
    command: |
      export PYTHON="$$JULIA_DEPOT_PATH/conda/3/bin/python"
      export PYTHONHOME="$$JULIA_DEPOT_PATH/conda/3/bin"
      export CONDA_JL_HOME="$$JULIA_DEPOT_PATH/conda/3"

      mkdir examples/Emulator/GaussianProcess/depot
      export JULIA_DEPOT_PATH="$$(pwd)/examples/Emulator/GaussianProcess/depot:$JULIA_DEPOT_PATH"

      julia --color=yes --project=examples/Emulator/GaussianProcess -e '
        println("--- Developing Project")
        using Pkg;
        Pkg.develop(path=".")
        println("--- Instantiating Project")
        Pkg.instantiate()
        println("+++ Running PlotGP")
        include("examples/Emulator/GaussianProcess/plot_GP.jl")
        println("+++ Running Learn Noise")
        include("examples/Emulator/GaussianProcess/learn_noise.jl")'
    artifact_paths:
      - "examples/Emulator/GaussianProcess/output/*.png"
    env:
      PYTHON: "$$JULIA_DEPOT_PATH/conda/3/bin/python"
      PYTHONHOME: "$$JULIA_DEPOT_PATH/conda/3/bin"
      CONDA_JL_HOME: "$$JULIA_DEPOT_PATH/conda/3"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

